// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: AstrOsScreen

#include "../ui.h"


void ui_event_comp_mainmodal_mainmodal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_mainmodal = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_CLICKED) {
        onModalClick(e);
    }
}

// COMPONENT MainModal

lv_obj_t * ui_mainmodal_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_mainmodal;
    cui_mainmodal = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_mainmodal);
    lv_obj_set_width(cui_mainmodal, 800);
    lv_obj_set_height(cui_mainmodal, 480);
    lv_obj_set_align(cui_mainmodal, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_mainmodal, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(cui_mainmodal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_coverpanel;
    cui_coverpanel = lv_obj_create(cui_mainmodal);
    lv_obj_set_width(cui_coverpanel, 800);
    lv_obj_set_height(cui_coverpanel, 480);
    lv_obj_set_align(cui_coverpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_coverpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_coverpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_coverpanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_coverpanel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_textpanel;
    cui_textpanel = lv_obj_create(cui_coverpanel);
    lv_obj_set_width(cui_textpanel, 400);
    lv_obj_set_height(cui_textpanel, 200);
    lv_obj_set_align(cui_textpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_textpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_message;
    cui_message = lv_label_create(cui_textpanel);
    lv_obj_set_width(cui_message, 360);
    lv_obj_set_height(cui_message, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_message, LV_ALIGN_CENTER);
    lv_label_set_text(cui_message, "This is a really long error message that will go on forever and ever and ever");
    lv_obj_set_style_text_font(cui_message, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_MAINMODAL_NUM);
    children[UI_COMP_MAINMODAL_MAINMODAL] = cui_mainmodal;
    children[UI_COMP_MAINMODAL_COVERPANEL] = cui_coverpanel;
    children[UI_COMP_MAINMODAL_COVERPANEL_TEXTPANEL] = cui_textpanel;
    children[UI_COMP_MAINMODAL_COVERPANEL_TEXTPANEL_MESSAGE] = cui_message;
    lv_obj_add_event_cb(cui_mainmodal, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_mainmodal, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_mainmodal, ui_event_comp_mainmodal_mainmodal, LV_EVENT_ALL, children);
    ui_comp_mainmodal_create_hook(cui_mainmodal);
    return cui_mainmodal;
}

