// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: AstrOsScreen

#ifndef _UI_COMP_MAINMODAL_H
#define _UI_COMP_MAINMODAL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT MainModal
#define UI_COMP_MAINMODAL_MAINMODAL 0
#define UI_COMP_MAINMODAL_COVERPANEL 1
#define UI_COMP_MAINMODAL_COVERPANEL_TEXTPANEL 2
#define UI_COMP_MAINMODAL_COVERPANEL_TEXTPANEL_MESSAGE 3
#define _UI_COMP_MAINMODAL_NUM 4
lv_obj_t * ui_mainmodal_create(lv_obj_t * comp_parent);
void ui_event_comp_mainmodal_mainmodal(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
