// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: AstrOsScreen

#include "../ui.h"

void ui_loadingscreen_screen_init(void)
{
    ui_loadingscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_loadingscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loadingscreen_spinner1 = lv_spinner_create(ui_loadingscreen, 1000, 90);
    lv_obj_set_width(ui_loadingscreen_spinner1, 80);
    lv_obj_set_height(ui_loadingscreen_spinner1, 80);
    lv_obj_set_x(ui_loadingscreen_spinner1, 0);
    lv_obj_set_y(ui_loadingscreen_spinner1, 50);
    lv_obj_set_align(ui_loadingscreen_spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_loadingscreen_spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_loadingscreen_label1 = lv_label_create(ui_loadingscreen);
    lv_obj_set_width(ui_loadingscreen_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loadingscreen_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_loadingscreen_label1, 0);
    lv_obj_set_y(ui_loadingscreen_label1, -130);
    lv_obj_set_align(ui_loadingscreen_label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_loadingscreen_label1, "Astr-os");
    lv_obj_set_style_text_font(ui_loadingscreen_label1, &ui_font_StarJedi_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loadingscreen_label2 = lv_label_create(ui_loadingscreen);
    lv_obj_set_width(ui_loadingscreen_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loadingscreen_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_loadingscreen_label2, 0);
    lv_obj_set_y(ui_loadingscreen_label2, -40);
    lv_obj_set_align(ui_loadingscreen_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_loadingscreen_label2, "Astromech Control System");
    lv_obj_set_style_text_font(ui_loadingscreen_label2, &ui_font_StarJedi_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loadingscreen_label3 = lv_label_create(ui_loadingscreen);
    lv_obj_set_width(ui_loadingscreen_label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loadingscreen_label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_loadingscreen_label3, 0);
    lv_obj_set_y(ui_loadingscreen_label3, 140);
    lv_obj_set_align(ui_loadingscreen_label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_loadingscreen_label3, "...System Initializing");
    lv_obj_set_style_text_font(ui_loadingscreen_label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
