// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: AstrOsScreen

#include "../ui.h"

void ui_mainscreen_screen_init(void)
{
    ui_mainscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mainscreen_btnscript1 = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_mainscreen_btnscript1, 210);
    lv_obj_set_height(ui_mainscreen_btnscript1, 100);
    lv_obj_set_x(ui_mainscreen_btnscript1, 40);
    lv_obj_set_y(ui_mainscreen_btnscript1, 100);

    ui_mainscreen_lblscript1 = lv_label_create(ui_mainscreen_btnscript1);
    lv_obj_set_width(ui_mainscreen_lblscript1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainscreen_lblscript1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mainscreen_lblscript1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_mainscreen_lblscript1, LV_LABEL_LONG_DOT);
    lv_obj_set_style_text_font(ui_mainscreen_lblscript1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainscreen_btnscript2 = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_mainscreen_btnscript2, 210);
    lv_obj_set_height(ui_mainscreen_btnscript2, 100);
    lv_obj_set_x(ui_mainscreen_btnscript2, 0);
    lv_obj_set_y(ui_mainscreen_btnscript2, 100);
    lv_obj_set_align(ui_mainscreen_btnscript2, LV_ALIGN_TOP_MID);

    ui_mainscreen_lblscript2 = lv_label_create(ui_mainscreen_btnscript2);
    lv_obj_set_width(ui_mainscreen_lblscript2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainscreen_lblscript2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mainscreen_lblscript2, -5);
    lv_obj_set_y(ui_mainscreen_lblscript2, 2);
    lv_obj_set_align(ui_mainscreen_lblscript2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_mainscreen_lblscript2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainscreen_btnscript3 = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_mainscreen_btnscript3, 210);
    lv_obj_set_height(ui_mainscreen_btnscript3, 100);
    lv_obj_set_x(ui_mainscreen_btnscript3, -40);
    lv_obj_set_y(ui_mainscreen_btnscript3, 100);
    lv_obj_set_align(ui_mainscreen_btnscript3, LV_ALIGN_TOP_RIGHT);

    ui_mainscreen_lblscript3 = lv_label_create(ui_mainscreen_btnscript3);
    lv_obj_set_width(ui_mainscreen_lblscript3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainscreen_lblscript3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mainscreen_lblscript3, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_mainscreen_lblscript3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainscreen_btnscript4 = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_mainscreen_btnscript4, 210);
    lv_obj_set_height(ui_mainscreen_btnscript4, 100);
    lv_obj_set_x(ui_mainscreen_btnscript4, 40);
    lv_obj_set_y(ui_mainscreen_btnscript4, 220);

    ui_mainscreen_lblscript4 = lv_label_create(ui_mainscreen_btnscript4);
    lv_obj_set_width(ui_mainscreen_lblscript4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainscreen_lblscript4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mainscreen_lblscript4, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_mainscreen_lblscript4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainscreen_btnscript5 = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_mainscreen_btnscript5, 210);
    lv_obj_set_height(ui_mainscreen_btnscript5, 100);
    lv_obj_set_x(ui_mainscreen_btnscript5, 0);
    lv_obj_set_y(ui_mainscreen_btnscript5, 220);
    lv_obj_set_align(ui_mainscreen_btnscript5, LV_ALIGN_TOP_MID);

    ui_mainscreen_lblscript5 = lv_label_create(ui_mainscreen_btnscript5);
    lv_obj_set_width(ui_mainscreen_lblscript5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainscreen_lblscript5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mainscreen_lblscript5, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_mainscreen_lblscript5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainscreen_btnscript6 = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_mainscreen_btnscript6, 210);
    lv_obj_set_height(ui_mainscreen_btnscript6, 100);
    lv_obj_set_x(ui_mainscreen_btnscript6, -40);
    lv_obj_set_y(ui_mainscreen_btnscript6, 220);
    lv_obj_set_align(ui_mainscreen_btnscript6, LV_ALIGN_TOP_RIGHT);

    ui_mainscreen_lblscript6 = lv_label_create(ui_mainscreen_btnscript6);
    lv_obj_set_width(ui_mainscreen_lblscript6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainscreen_lblscript6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mainscreen_lblscript6, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_mainscreen_lblscript6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainscreen_btnscript7 = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_mainscreen_btnscript7, 210);
    lv_obj_set_height(ui_mainscreen_btnscript7, 100);
    lv_obj_set_x(ui_mainscreen_btnscript7, 40);
    lv_obj_set_y(ui_mainscreen_btnscript7, 340);

    ui_mainscreen_lblscript7 = lv_label_create(ui_mainscreen_btnscript7);
    lv_obj_set_width(ui_mainscreen_lblscript7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainscreen_lblscript7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mainscreen_lblscript7, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_mainscreen_lblscript7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainscreen_btnscript8 = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_mainscreen_btnscript8, 210);
    lv_obj_set_height(ui_mainscreen_btnscript8, 100);
    lv_obj_set_x(ui_mainscreen_btnscript8, 0);
    lv_obj_set_y(ui_mainscreen_btnscript8, 340);
    lv_obj_set_align(ui_mainscreen_btnscript8, LV_ALIGN_TOP_MID);

    ui_mainscreen_lblscript8 = lv_label_create(ui_mainscreen_btnscript8);
    lv_obj_set_width(ui_mainscreen_lblscript8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainscreen_lblscript8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mainscreen_lblscript8, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_mainscreen_lblscript8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainscreen_btnscript9 = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_mainscreen_btnscript9, 210);
    lv_obj_set_height(ui_mainscreen_btnscript9, 100);
    lv_obj_set_x(ui_mainscreen_btnscript9, -40);
    lv_obj_set_y(ui_mainscreen_btnscript9, 340);
    lv_obj_set_align(ui_mainscreen_btnscript9, LV_ALIGN_TOP_RIGHT);

    ui_mainscreen_lblscript9 = lv_label_create(ui_mainscreen_btnscript9);
    lv_obj_set_width(ui_mainscreen_lblscript9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainscreen_lblscript9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mainscreen_lblscript9, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_mainscreen_lblscript9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainscreen_btnpanicstop = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_mainscreen_btnpanicstop, 220);
    lv_obj_set_height(ui_mainscreen_btnpanicstop, 70);
    lv_obj_set_x(ui_mainscreen_btnpanicstop, 0);
    lv_obj_set_y(ui_mainscreen_btnpanicstop, 10);
    lv_obj_set_align(ui_mainscreen_btnpanicstop, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_mainscreen_btnpanicstop, lv_color_hex(0xB81C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainscreen_btnpanicstop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainscreen_lblpanicstop = lv_label_create(ui_mainscreen_btnpanicstop);
    lv_obj_set_width(ui_mainscreen_lblpanicstop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainscreen_lblpanicstop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mainscreen_lblpanicstop, 1);
    lv_obj_set_y(ui_mainscreen_lblpanicstop, -3);
    lv_obj_set_align(ui_mainscreen_lblpanicstop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mainscreen_lblpanicstop, "panic stop");
    lv_obj_set_style_text_font(ui_mainscreen_lblpanicstop, &ui_font_StarJedi_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainscreen_btnback = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_mainscreen_btnback, 120);
    lv_obj_set_height(ui_mainscreen_btnback, 70);
    lv_obj_set_x(ui_mainscreen_btnback, 40);
    lv_obj_set_y(ui_mainscreen_btnback, 10);
    lv_obj_set_style_bg_color(ui_mainscreen_btnback, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainscreen_btnback, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainscreen_image1 = lv_img_create(ui_mainscreen_btnback);
    lv_img_set_src(ui_mainscreen_image1, &ui_img_button_png);
    lv_obj_set_width(ui_mainscreen_image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainscreen_image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mainscreen_image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainscreen_image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mainscreen_image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mainscreen_btnforward = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_mainscreen_btnforward, 120);
    lv_obj_set_height(ui_mainscreen_btnforward, 70);
    lv_obj_set_x(ui_mainscreen_btnforward, -40);
    lv_obj_set_y(ui_mainscreen_btnforward, 10);
    lv_obj_set_align(ui_mainscreen_btnforward, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(ui_mainscreen_btnforward, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainscreen_btnforward, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainscreen_image2 = lv_img_create(ui_mainscreen_btnforward);
    lv_img_set_src(ui_mainscreen_image2, &ui_img_button_png);
    lv_obj_set_width(ui_mainscreen_image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainscreen_image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mainscreen_image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainscreen_image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mainscreen_image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_mainscreen_image2, 1800);

    ui_mainscreen_btnwifi = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_mainscreen_btnwifi, 70);
    lv_obj_set_height(ui_mainscreen_btnwifi, 70);
    lv_obj_set_x(ui_mainscreen_btnwifi, 200);
    lv_obj_set_y(ui_mainscreen_btnwifi, 10);
    lv_obj_set_style_radius(ui_mainscreen_btnwifi, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainscreen_btnwifi, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainscreen_btnwifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainscreen_btnsettings = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_mainscreen_btnsettings, 70);
    lv_obj_set_height(ui_mainscreen_btnsettings, 70);
    lv_obj_set_x(ui_mainscreen_btnsettings, -200);
    lv_obj_set_y(ui_mainscreen_btnsettings, 10);
    lv_obj_set_align(ui_mainscreen_btnsettings, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_radius(ui_mainscreen_btnsettings, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainscreen_btnsettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainscreen_btnsettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainscreen_image3 = lv_img_create(ui_mainscreen_btnsettings);
    lv_img_set_src(ui_mainscreen_image3, &ui_img_gear_png);
    lv_obj_set_width(ui_mainscreen_image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainscreen_image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mainscreen_image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainscreen_image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mainscreen_image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mainscreen_mainmodal = ui_mainmodal_create(ui_mainscreen);
    lv_obj_set_x(ui_mainscreen_mainmodal, 0);
    lv_obj_set_y(ui_mainscreen_mainmodal, 0);





    lv_obj_add_event_cb(ui_mainscreen_btnscript1, ui_event_mainscreen_btnscript1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainscreen_btnscript2, ui_event_mainscreen_btnscript2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainscreen_btnscript3, ui_event_mainscreen_btnscript3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainscreen_btnscript4, ui_event_mainscreen_btnscript4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainscreen_btnscript5, ui_event_mainscreen_btnscript5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainscreen_btnscript6, ui_event_mainscreen_btnscript6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainscreen_btnscript7, ui_event_mainscreen_btnscript7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainscreen_btnscript8, ui_event_mainscreen_btnscript8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainscreen_btnscript9, ui_event_mainscreen_btnscript9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainscreen_btnpanicstop, ui_event_mainscreen_btnpanicstop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainscreen_btnback, ui_event_mainscreen_btnback, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainscreen_btnforward, ui_event_mainscreen_btnforward, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainscreen_btnsettings, ui_event_mainscreen_btnsettings, LV_EVENT_ALL, NULL);

}
