// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: AstrOsScreen

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onScript1(lv_event_t * e);
void onScript2(lv_event_t * e);
void onScript3(lv_event_t * e);
void onScript4(lv_event_t * e);
void onScript5(lv_event_t * e);
void onScript6(lv_event_t * e);
void onScript7(lv_event_t * e);
void onScript8(lv_event_t * e);
void onScript9(lv_event_t * e);
void onPanicStop(lv_event_t * e);
void onBack(lv_event_t * e);
void onForward(lv_event_t * e);
void onModalClick(lv_event_t * e);
void onCbxSSIDChanged(lv_event_t * e);
void onWifiScan(lv_event_t * e);
void onWifiConnect(lv_event_t * e);
void onSyncScripts(lv_event_t * e);
void onKbdPressed(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
